# This is a basic workflow to help you get started with Actions


name: Sync Commits

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Hello World"



