name: Sync Commits

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo1
        uses: actions/checkout@v2

      - name: Check for changes
        id: git-diff
        run: echo "::set-output name=changes::$(git diff --name-only HEAD^ HEAD)"

      - name: Push changed files to repo2
        if: steps.git-diff.outputs.changes != ''
        uses: actions/checkout@v2
        with:
          repository: dhruvraapid/repo2
          token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "dhruv@raapid.ai"
          git config --global user.name "Dhruv Patel"
          git add .
          git commit -m "Sync changes from repo1"
          git push origin main
