name: Sync Commits

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo1
        uses: actions/checkout@v2

      - name: Check for changes
        id: git-diff
        run: echo "::set-output name=changes::$(git diff --name-only HEAD^ HEAD)"

      - name: Push changed files to repo2
        if: steps.git-diff.outputs.changes != ''
        run: |
          git remote add repo2 https://github.com/dhruvraapid/repo2.git
          git add .
          git commit -m "Sync changes from repo1"
          git push repo2 main
